from sqlalchemy import select
from sqlalchemy.engine import Engine
from sqlalchemy.orm import Session

from app.models.term import Term
from app.models.relation import Relation
from app.services import user_service

# Тестовый набор терминов (~50 записей)
TERMS = [
    dict(term_ru="Популяционная геномика", term_en="Population genomics",
         definition="Исследование вариаций в геномах целых популяций для реконструкции истории и адаптаций.",
         context="Используется для анализа миграций, смешения популяций и выявления адаптивных сигналов.",
         definition_en="Study of genome-wide variation across populations to reconstruct history and adaptations.",
         context_en="Used to analyze migration, admixture, and detect adaptive signals."),
    dict(term_ru="Митохондриальная ДНК", term_en="Mitochondrial DNA",
         definition="Кольцевая молекула ДНК в митохондриях, наследуется по материнской линии.",
         context="Применяется для отслеживания материнских линий и древних миграций.",
         definition_en="Circular DNA molecule in mitochondria, inherited maternally.",
         context_en="Used to trace maternal lineages and ancient migrations.", abbreviation="mtDNA"),
    dict(term_ru="Y-хромосомные маркеры", term_en="Y-chromosome markers",
         definition="Маркерные SNP и STR на Y-хромосоме, наследуемые по отцовской линии.",
         context="Используются для исследования патрилинейных связей и мужских миграций.",
         definition_en="Marker SNPs and STRs on the Y chromosome inherited paternally.",
         context_en="Used to study patrilineal lineages and male migrations.", abbreviation="Y-SNP"),
    dict(term_ru="Аутосомный SNP", term_en="Autosomal SNP",
         definition="Однонуклеотидный полиморфизм в аутосомах, отражающий смешанную наследственность.",
         context="Подходит для оценки долей происхождения и расчета генетической дистанции.",
         definition_en="Single nucleotide polymorphism in autosomes reflecting mixed ancestry.",
         context_en="Suitable for ancestry proportions and genetic distance."),
    dict(term_ru="Гаплогруппа", term_en="Haplogroup",
         definition="Совокупность родственных гаплотипов, происходящих от общего предка.",
         context="Классификация линий mtDNA и Y-хромосомы в популяционных исследованиях.",
         definition_en="Set of related haplotypes descending from a common ancestor.",
         context_en="Used to classify mtDNA and Y-chromosome lineages.", abbreviation="HG"),
    dict(term_ru="Генетический дрейф", term_en="Genetic drift",
         definition="Случайные изменения частот аллелей в популяции, накапливающиеся со временем.",
         context="Наиболее заметен в малых и изолированных группах.",
         definition_en="Random changes in allele frequencies over time.",
         context_en="Most noticeable in small and isolated populations."),
    dict(term_ru="Основательский эффект", term_en="Founder effect",
         definition="Снижение генетического разнообразия из-за происхождения популяции от малого числа предков.",
         context="Может приводить к необычным частотам аллелей и редким заболеваниям.",
         definition_en="Reduction of genetic diversity when a population descends from few founders.",
         context_en="Can lead to unusual allele frequencies and rare diseases."),
    dict(term_ru="Антропогенетика", term_en="Anthropogenetics",
         definition="Изучение генетических особенностей человека в эволюционном и этническом контексте.",
         context="Соединяет антропологию и генетику для анализа происхождения и миграций.",
         definition_en="Study of human genetic features in evolutionary and ethnic context.",
         context_en="Combines anthropology and genetics to analyze origins and migrations."),
    dict(term_ru="Генетический маркер", term_en="Genetic marker",
         definition="Участок ДНК с известной вариацией, используемый для идентификации и сопоставления.",
         context="Применяется в картах генома, анализе родства и популяционных исследованиях.",
         definition_en="DNA locus with known variation used for identification and mapping.",
         context_en="Used in genome maps, kinship, and population studies."),
    dict(term_ru="Гаплотип", term_en="Haplotype",
         definition="Набор совместно наследуемых аллелей на одной хромосоме.",
         context="Ключевой элемент для реконструкции родословных и происхождения линий.",
         definition_en="Set of alleles inherited together on one chromosome.",
         context_en="Key element for lineage reconstruction and origin analysis."),
    dict(term_ru="Y-гаплогруппа R1a", term_en="Y-haplogroup R1a",
         definition="Патрилинейная гаплогруппа, распространённая в Восточной Европе и Южной Азии.",
         context="Используется для изучения миграций индоевропейских популяций.",
         definition_en="Paternal haplogroup common in Eastern Europe and South Asia.",
         context_en="Used to study migrations of Indo-European populations.", abbreviation="R1a"),
    dict(term_ru="Y-гаплогруппа R1b", term_en="Y-haplogroup R1b",
         definition="Патрилинейная гаплогруппа, доминирующая в Западной Европе.",
         context="Служит маркером для отслеживания западноевропейских линий.",
         definition_en="Paternal haplogroup dominant in Western Europe.",
         context_en="Marker for tracing Western European lineages.", abbreviation="R1b"),
    dict(term_ru="Y-гаплогруппа J2", term_en="Y-haplogroup J2",
         definition="Группа, связанная с Ближним Востоком и Средиземноморьем.",
         context="Используется для изучения неолитических земледельцев и торговых путей.",
         definition_en="Haplogroup linked to the Near East and Mediterranean.",
         context_en="Used to study Neolithic farmers and trade routes.", abbreviation="J2"),
    dict(term_ru="Y-гаплогруппа E1b1b", term_en="Y-haplogroup E1b1b",
         definition="Гаплогруппа с высоким разнообразием в Северной Африке и Европе.",
         context="Маркер для исследований афро-европейских контактов.",
         definition_en="Haplogroup with high diversity in North Africa and Europe.",
         context_en="Marker for Afro-European contacts.", abbreviation="E1b1b"),
    dict(term_ru="Y-гаплогруппа N1c", term_en="Y-haplogroup N1c",
         definition="Гаплогруппа, характерная для финно-угорских и североевразийских народов.",
         context="Используется для изучения расселения по северным маршрутам.",
         definition_en="Haplogroup characteristic for Finno-Ugric and North Eurasian peoples.",
         context_en="Used to study northern dispersal routes.", abbreviation="N1c"),
    dict(term_ru="Y-гаплогруппа Q", term_en="Y-haplogroup Q",
         definition="Патрилинейная линия, связанная с миграцией в Америку и Сибирь.",
         context="Маркер для анализа древних переходов через Берингийский перешеек.",
         definition_en="Paternal lineage linked to migration into the Americas and Siberia.",
         context_en="Marker for ancient Beringian crossings.", abbreviation="Q"),
    dict(term_ru="mtDNA гаплогруппа H", term_en="mtDNA haplogroup H",
         definition="Одна из наиболее распространённых материнских линий Европы.",
         context="Используется в исследованиях постледниковых репопуляций.",
         definition_en="One of the most common maternal lineages in Europe.",
         context_en="Used in studies of post-glacial repopulations."),
    dict(term_ru="mtDNA гаплогруппа U", term_en="mtDNA haplogroup U",
         definition="Старая европейская материнская линия, обнаруживаемая у древних охотников-собирателей.",
         context="Маркер для реконструкции мезолитических популяций.",
         definition_en="Ancient European maternal lineage found in hunter-gatherers.",
         context_en="Marker to reconstruct Mesolithic populations."),
    dict(term_ru="mtDNA гаплогруппа K", term_en="mtDNA haplogroup K",
         definition="Материнская линия, часто связанная с неолитическими земледельцами.",
         context="Используется для отслеживания распространения земледелия.",
         definition_en="Maternal lineage often linked to Neolithic farmers.",
         context_en="Used to trace the spread of farming."),
    dict(term_ru="mtDNA гаплогруппа T", term_en="mtDNA haplogroup T",
         definition="Материнская линия Евразии с широким географическим распределением.",
         context="Отмечается в анализах миграций степных культур.",
         definition_en="Maternal Eurasian lineage with broad distribution.",
         context_en="Noted in analyses of steppe migrations."),
    dict(term_ru="Древняя ДНК", term_en="Ancient DNA",
         definition="Генетический материал, извлечённый из археологических образцов.",
         context="Позволяет напрямую изучать геном древних популяций.",
         definition_en="Genetic material extracted from archaeological samples.",
         context_en="Enables direct study of ancient genomes."),
    dict(term_ru="Молекулярные часы", term_en="Molecular clock",
         definition="Метод оценки времени дивергенции по скорости мутаций.",
         context="Применяется для датировки разделения линий и миграций.",
         definition_en="Method estimating divergence time via mutation rate.",
         context_en="Used to date lineage splits and migrations."),
    dict(term_ru="Эффективная численность популяции", term_en="Effective population size",
         definition="Число особей, участвующих в воспроизводстве и определяющих генетическое разнообразие.",
         context="Ключевая метрика для моделирования дрейфа и отбора.",
         definition_en="Number of individuals contributing to reproduction and diversity.",
         context_en="Key metric for modeling drift and selection."),
    dict(term_ru="Генетическое бутылочное горлышко", term_en="Genetic bottleneck",
         definition="Резкое сокращение численности и генетического разнообразия популяции.",
         context="Выявляется по снижению гетерозиготности и росту родства.",
         definition_en="Sharp reduction of population size and genetic diversity.",
         context_en="Detected by decreased heterozygosity and increased relatedness."),
    dict(term_ru="Экспансия популяции", term_en="Population expansion",
         definition="Быстрый рост численности, оставляющий сигнатуру в спектре частот аллелей.",
         context="Моделируется при анализе миграций и демографической истории.",
         definition_en="Rapid growth leaving a signature in allele frequency spectrum.",
         context_en="Modeled in migration and demographic analyses."),
    dict(term_ru="Смешение популяций", term_en="Admixture",
         definition="Объединение генетических пулов разных групп.",
         context="Определяется методами f-статистик, qpAdm, ADMIXTURE.",
         definition_en="Mixing of genetic pools from different groups.",
         context_en="Identified via f-stats, qpAdm, ADMIXTURE."),
    dict(term_ru="Адаптивная интрогрессия", term_en="Adaptive introgression",
         definition="Передача адаптивных аллелей между популяциями через смешение.",
         context="Изучается на примере неандертальских и денисовских вкладов.",
         definition_en="Transfer of adaptive alleles via admixture.",
         context_en="Studied in Neanderthal and Denisovan contributions."),
    dict(term_ru="Интрогрессия", term_en="Introgression",
         definition="Включение генов одной популяции в геном другой через гибридизацию.",
         context="Оценивается по локусам с необычным происхождением.",
         definition_en="Incorporation of genes via hybridization.",
         context_en="Assessed by loci with unusual ancestry."),
    dict(term_ru="Миграция популяций", term_en="Population migration",
         definition="Перемещение групп, формирующее новые генетические паттерны.",
         context="Реконструируется по сигналам смешения и структуре генофонда.",
         definition_en="Movement of groups shaping genetic patterns.",
         context_en="Reconstructed from admixture signals and gene pool structure."),
    dict(term_ru="Структура популяции", term_en="Population structure",
         definition="Наличие субпопуляций с различающимися частотами аллелей.",
         context="Учитывается при ассоциативных исследованиях и анализе родства.",
         definition_en="Presence of subpopulations with distinct allele frequencies.",
         context_en="Accounted for in association and kinship analyses."),
    dict(term_ru="Кластерный анализ", term_en="Cluster analysis",
         definition="Группировка индивидов по генетическому сходству.",
         context="Используется в построении дендрограмм и популяционных кластеров.",
         definition_en="Grouping individuals by genetic similarity.",
         context_en="Used to build dendrograms and population clusters."),
    dict(term_ru="PCA-анализ", term_en="PCA analysis",
         definition="Метод главных компонентов для визуализации генетической структуры.",
         context="Позволяет увидеть градиенты и группы в высокомерных данных.",
         definition_en="Principal component analysis to visualize genetic structure.",
         context_en="Reveals gradients and clusters in high-dimensional data.",
         abbreviation="PCA"),
    dict(term_ru="ADMIXTURE-анализ", term_en="ADMIXTURE analysis",
         definition="Оценка компонент происхождения на основе вероятностной модели.",
         context="Помогает выявлять доли разных источников у индивидов.",
         definition_en="Estimation of ancestry components via probabilistic model.",
         context_en="Helps detect proportions of different sources in individuals."),
    dict(term_ru="Филогеография", term_en="Phylogeography",
         definition="Связь филогенетических линий с географическим распределением.",
         context="Применяется для картирования миграционных путей.",
         definition_en="Linking phylogenetic lineages to geographic distribution.",
         context_en="Used to map migration routes."),
    dict(term_ru="Филогенетика", term_en="Phylogenetics",
         definition="Реконструкция эволюционных отношений между линиями.",
         context="Строит деревья на основе последовательностей ДНК.",
         definition_en="Reconstruction of evolutionary relationships.",
         context_en="Builds trees from DNA sequences."),
    dict(term_ru="Метапопуляция", term_en="Metapopulation",
         definition="Совокупность субпопуляций с ограниченным обменом генами.",
         context="Модель для описания динамики фрагментированных групп.",
         definition_en="Set of subpopulations with limited gene flow.",
         context_en="Model for fragmented population dynamics."),
    dict(term_ru="Генетический ландшафт", term_en="Genetic landscape",
         definition="Пространственное распределение генетического разнообразия.",
         context="Визуализируется через карты частот и FST.",
         definition_en="Spatial distribution of genetic diversity.",
         context_en="Visualized via frequency maps and FST."),
    dict(term_ru="Генофонд", term_en="Gene pool",
         definition="Совокупность всех аллелей популяции.",
         context="Используется для оценки разнообразия и изменений во времени.",
         definition_en="Sum of all alleles in a population.",
         context_en="Used to assess diversity and temporal change."),
    dict(term_ru="Микросателлит (STR)", term_en="Microsatellite (STR)",
         definition="Короткие тандемные повторы, высоковариабельные маркеры.",
         context="Применяются в криминалистике и исследовании родства.",
         definition_en="Short tandem repeats, highly variable markers.",
         context_en="Used in forensics and kinship.",
         abbreviation="STR"),
    dict(term_ru="Диагностический SNP", term_en="Diagnostic SNP",
         definition="Полиморфизм, отличающий одну линию или популяцию от другой.",
         context="Используется для атрибуции происхождения.",
         definition_en="Polymorphism distinguishing one lineage or population.",
         context_en="Used for ancestry attribution."),
    dict(term_ru="Контаминация ДНК", term_en="DNA contamination",
         definition="Примесь чужой ДНК в образце.",
         context="Особенно критична для ancient DNA; требует контроля лабораторных процедур.",
         definition_en="Presence of foreign DNA in a sample.",
         context_en="Critical for aDNA; requires strict lab controls."),
    dict(term_ru="Контроль качества данных", term_en="Data quality control",
         definition="Набор процедур для фильтрации ошибок в последовательностях и генотипах.",
         context="Включает фильтры по покрытию, дупликатам, повреждениям.",
         definition_en="Procedures to filter errors in sequences and genotypes.",
         context_en="Includes coverage, duplicates, damage filters."),
    dict(term_ru="Покрытие секвенирования", term_en="Sequencing coverage",
         definition="Среднее количество чтений, перекрывающих позицию генома.",
         context="Влияет на точность выявления вариантов.",
         definition_en="Average number of reads covering a genome position.",
         context_en="Affects variant call accuracy."),
    dict(term_ru="Средняя длина чтения", term_en="Mean read length",
         definition="Средняя длина секвенированных фрагментов.",
         context="Короткие чтения могут ухудшать сборку и выравнивание.",
         definition_en="Average length of sequenced fragments.",
         context_en="Short reads may hinder assembly and alignment."),
    dict(term_ru="Частота минорного аллеля", term_en="Minor allele frequency",
         definition="Доля реже встречающегося аллеля в популяции.",
         context="Используется при фильтрации редких и частых вариантов.",
         definition_en="Frequency of the less common allele in a population.",
         context_en="Used to filter rare/common variants.",
         abbreviation="MAF"),
    dict(term_ru="Тест Харди-Вайнберга", term_en="Hardy-Weinberg test",
         definition="Проверка соответствия генотипных частот равновесию.",
         context="Позволяет выявлять ошибки генотипирования и отбор.",
         definition_en="Test for conformance to Hardy-Weinberg equilibrium.",
         context_en="Flags genotyping errors and selection."),
    dict(term_ru="FST", term_en="FST",
         definition="Мера дифференциации популяций по частотам аллелей.",
         context="Высокие значения указывают на ограниченный генетический обмен.",
         definition_en="Measure of population differentiation by allele frequencies.",
         context_en="High values indicate limited gene flow.",
         abbreviation="FST"),
    dict(term_ru="Identity by descent", term_en="Identity by descent",
         definition="Совпадение участков ДНК, унаследованных от общего предка.",
         context="Используется для оценки родства и демографии.",
         definition_en="Shared DNA segments inherited from a common ancestor.",
         context_en="Used for relatedness and demographic inference.",
         abbreviation="IBD"),
    dict(term_ru="Identity by state", term_en="Identity by state",
         definition="Совпадение аллелей без подтверждения общего предка.",
         context="Отличается от IBD отсутствием информации о родстве.",
         definition_en="Alleles match without evidence of common ancestor.",
         context_en="Differs from IBD by lacking relatedness info.",
         abbreviation="IBS"),
    dict(term_ru="Референсная панель", term_en="Reference panel",
         definition="Набор генотипов с известным происхождением для иммутации и сравнений.",
         context="Например, 1000 Genomes или локальные панели.",
         definition_en="Set of genotypes with known ancestry for imputation and comparison.",
         context_en="E.g., 1000 Genomes or local panels.")
]

RELATIONS = [
    dict(term_index=4, related_index=2, type="paternal"),  # Haplogroup -> Y markers
    dict(term_index=4, related_index=1, type="maternal"),  # Haplogroup -> mtDNA
    dict(term_index=3, related_index=0, type="feature"),   # Autosomal SNP -> Population genomics
    dict(term_index=5, related_index=6, type="cause"),     # Genetic drift -> Founder effect
    dict(term_index=0, related_index=5, type="process"),   # Population genomics -> Genetic drift
    # Лексикографические связи
    dict(term_index=9, related_index=4, type="hyponym"),    # Haplotype -> Haplogroup
    dict(term_index=4, related_index=9, type="hypernym"),   # Haplogroup -> Haplotype
    dict(term_index=8, related_index=39, type="synonym"),   # Genetic marker ~ Diagnostic SNP
    dict(term_index=23, related_index=24, type="antonym"),  # Bottleneck vs Expansion
    dict(term_index=10, related_index=4, type="hyponym"),   # R1a -> Haplogroup
    dict(term_index=11, related_index=4, type="hyponym"),   # R1b -> Haplogroup
    dict(term_index=12, related_index=4, type="hyponym"),   # J2 -> Haplogroup
    dict(term_index=13, related_index=4, type="hyponym"),   # E1b1b -> Haplogroup
    dict(term_index=14, related_index=4, type="hyponym"),   # N1c -> Haplogroup
    dict(term_index=15, related_index=4, type="hyponym"),   # Q -> Haplogroup
]


def seed_initial_data(engine: Engine) -> None:
    with Session(engine) as session:
        # Если данные уже есть, лишь гарантируем наличие администратора
        if session.scalar(select(Term.id).limit(1)):
            user_service.ensure_default_admin(session)
            return

        term_objs = [Term(**data) for data in TERMS]
        session.add_all(term_objs)
        session.flush()

        relations = [
            Relation(term_id=term_objs[r["term_index"]].id, related_id=term_objs[r["related_index"]].id, type=r["type"])
            for r in RELATIONS
        ]
        session.add_all(relations)
        session.commit()
        user_service.ensure_default_admin(session)
